### ISSUE TITLE
[chord] handle nodes dropping - ungracefully - from the chord

### ISSUE THREAD

**Issue by heidiklum** [bushidocodes/chord-grpc#10]
i.e., fault tolerance

**Comment by heidiklum** [comment]
remember to update find_successor() per IEEE paper:

"If a node fails during the 'find_successor' procedure, the lookup proceeds, after a timeout, by trying the next best predecessor among the nodes in the finger table and the successor list."

**Comment by heidiklum** [comment]
consider fortifying closest_preceding_node() per the IEEE paper:

"A modified version of the 'closest_preceding_node' procedure in Fig. 5 searches not only the finger table but also the successor list for the most immediate predecessor of ID."

**Comment by bushidocodes** [comment]
@heidiklum - What is the status on this one? Is this implemented or still open?

**Comment by bushidocodes** [comment]
Resolved by #32
