### ISSUE TITLE
Use SHA-1 Hashing API in Chord Algorithms

### ISSUE THREAD

**Issue by bushidocodes** [bushidocodes/chord-grpc#13]

**Comment by heidiklum** [comment]
The _self now can compute its own ID based on a truncated SHA-1 hash if the "--id" parameters isn't provided.  The hash is computed over the concatenation of "_self.ip + _self.port".

The code can be tested as follows:



#!/bin/bash

# directory containing node.js
WORKING_DIR="/home/test/Documents/chord/chord-grpc"

# known collision-free ports
# 0 --> 7; 1 --> 0; 4 --> 3; 6 --> 4; 8 --> 1; 10 --> 5; 11 --> 6
NODE_ID_NO_COLLISION=(0 1 4 6 8 10 11 14)

# use same hash length as in the chord-grpc node.js constant
HASH_BIT_LENGTH=3
# number of seconds to wait for a chord node to stabilize
#    intended to be >2 times the period at which stabilize() is called in node.js
STABILIZATION_INTERVAL=7

node_port=8440
node_id=7
known_node_port=8440
known_node_id=7
echo "Joining node ${node_id} to node ${known_node_id} ..."
gnome-terminal --geometry=+0+0 --title="Node ${node_id}" --working-directory="${WORKING_DIR}" -- \
	node node --ip localhost --port ${node_port} \
	--targetIp localhost --targetPort ${known_node_port} --targetId ${known_node_id}
sleep $STABILIZATION_INTERVAL

if [ $# -gt 0 ]; then
	# start the crawler on port 1337
	gnome-terminal --geometry=-0+0 --title="Crawler" --working-directory="${WORKING_DIR}" -- \
		node client crawl --ip localhost --port ${known_node_port} --webPort 1337
	sleep 3

	# browse to the crawler
	google-chrome -incognito --password-store=basic --new-window http://localhost:1337 &
	sleep 1
fi

node_port=8441
node_id=0
known_node_port=8440
known_node_id=7
echo "Joining node ${node_id} to node ${known_node_id} ..."
gnome-terminal --geometry=+0+0 --title="Node ${node_id}" --working-directory="${WORKING_DIR}" -- \
	node node --ip localhost --port ${node_port} \
	--targetIp localhost --targetPort ${known_node_port} --targetId ${known_node_id}
sleep $STABILIZATION_INTERVAL

node_port=8444
node_id=3
known_node_port=8440
known_node_id=7
echo "Joining node ${node_id} to node ${known_node_id} ..."
gnome-terminal --geometry=+0+0 --title="Node ${node_id}" --working-directory="${WORKING_DIR}" -- \
	node node --ip localhost --port ${node_port} \
	--targetIp localhost --targetPort ${known_node_port} --targetId ${known_node_id}
sleep $STABILIZATION_INTERVAL

node_port=8446
node_id=4
known_node_port=8444
known_node_id=3
echo "Joining node ${node_id} to node ${known_node_id} ..."
gnome-terminal --geometry=+0+0 --title="Node ${node_id}" --working-directory="${WORKING_DIR}" -- \
	node node --ip localhost --port ${node_port} \
	--targetIp localhost --targetPort ${known_node_port} --targetId ${known_node_id}
sleep $STABILIZATION_INTERVAL

node_port=8448
node_id=1
known_node_port=8444
known_node_id=3
echo "Joining node ${node_id} to node ${known_node_id} ..."
gnome-terminal --geometry=+0+0 --title="Node ${node_id}" --working-directory="${WORKING_DIR}" -- \
	node node --ip localhost --port ${node_port} \
	--targetIp localhost --targetPort ${known_node_port} --targetId ${known_node_id}
sleep $STABILIZATION_INTERVAL

node_port=8450
node_id=5
known_node_port=8444
known_node_id=3
echo "Joining node ${node_id} to node ${known_node_id} ..."
gnome-terminal --geometry=+0+0 --title="Node ${node_id}" --working-directory="${WORKING_DIR}" -- \
	node node --ip localhost --port ${node_port} \
	--targetIp localhost --targetPort ${known_node_port} --targetId ${known_node_id}
sleep $STABILIZATION_INTERVAL

node_port=8451
node_id=6
known_node_port=8444
known_node_id=3
echo "Joining node ${node_id} to node ${known_node_id} ..."
gnome-terminal --geometry=+0+0 --title="Node ${node_id}" --working-directory="${WORKING_DIR}" -- \
	node node --ip localhost --port ${node_port} \
	--targetIp localhost --targetPort ${known_node_port} --targetId ${known_node_id}
sleep $STABILIZATION_INTERVAL

**Comment by heidiklum** [comment]
The _self now can compute the ID of the knownNode based on a truncated SHA-1 hash if the "--targetId" parameters isn't provided. The hash is computed over the concatenation of - essentially - "args.targetIp + args.targetPort".  I said "essentially" becase I added new variables of knownIp and knownPort to make them easier to use - and eventually sanitize those inputs a bit more...though they are already compared against default values, just in case.

**Comment by heidiklum** [comment]
the first node could be executed as:
node node --ip localhost --port 8440 --targetIp localhost --targetPort 8440

subsequent nodes could be:
node node --ip localhost --port 8444 --targetIp localhost --targetPort 8440

as shown in the attached driver - where the optional "1" starts the crawler and browser
./driver_hash_manual.sh 1

[driver_hash_manual.sh.txt](https://github.com/bushidocodes/chord-grpc/files/3844698/driver_hash_manual.sh.txt)
