### ISSUE TITLE
[chord] handle nodes leaving - gracefully - from the chord

### ISSUE THREAD

**Issue by heidiklum** [bushidocodes/chord-grpc#14]
e.g., notifications and hooks for data migration

**Comment by heidiklum** [comment]
Depends on #10

**Comment by bushidocodes** [comment]
@heidiklum - This is complete, right?

**Comment by albero94** [comment]
Unless Naim says something different. I believe this is not implemented.

In my opinion, leaving gracefully means that you call migrateKeysBeforeLeaving( ), you make your predecessor and successor poin to each other, and then exit the chord (stop the application)

I think we could discuss skipping making the predecessor and successor nodes point to each other, but the migration is necessary.

**Comment by heidiklum** [comment]
I concur with Alvaro.  This was definitely not done until today, since it's what I have been working on since the last PR.  However, I believe that - at least for Linux - this is now happy on PR #86 .  See extensive commentary on the PR for context.  The logic seems right but the actual event handler that calls the logic has to be tested on Windows.  I saw several postings on stackoverflow about how to bolster the event handler if Windows doesn't like it.
