### ISSUE TITLE
Use hashing in Data API functions

### ISSUE THREAD

**Issue by albero94** [bushidocodes/chord-grpc#43]
The data API is using the user ID as the key instead of hashing the user or the user name.

**Comment by heidiklum** [comment]
see comment in:
https://gwchordgrpc.slack.com/archives/CQ3JERDHB/p1575698558004000
regarding commit https://github.com/bushidocodes/chord-grpc/commit/0b45f04d2215cce8cd5fd617af34366f72b906be

**Comment by heidiklum** [comment]
upon discussion with Sean, he suggested hashing the user id since that is intended to be unique.  the idea of the hash is to smear out the users if the user id is assigned, for example, sequentially, in which case some nodes would be heavily loaded while most might be empty.
