### ISSUE TITLE
Data API: with 32 bits of hash table users don't get added correctly

### ISSUE THREAD

**Issue by albero94** [bushidocodes/chord-grpc#70]
I have tried inserting users with different IDs while having three nodes running. These users should have been inserted in different nodes but they all ended up in the same one.

In some cases with big IDs, the ID saved did not correspond to the one I was sending and I even got negative IDs. 

Although this could be because I exceeded the int 32 size, one of the userIDs was NodeID + 1.

More testing is needed to exactly identify the problem but something is going on there.

**Comment by heidiklum** [comment]
Is this still an issue?

**Comment by bushidocodes** [comment]
I'm pretty sure that this was just because we hadn't yet implemented hashing in the data APIs. Closing
