### ISSUE TITLE
Data Migration: Node joining cluster

### ISSUE THREAD

**Issue by Ippotns** [bushidocodes/chord-grpc#8]
Depends on #9

Take a portion of the successor's data

**Comment by Ippotns** [comment]
Depends on #9

**Comment by heidiklum** [comment]
I had left a call to a dummy "migrateKeys()" method in the "join()" body.  You may want to leverage that to test the case of an incoming node pulling the data from an existing node.

**Comment by bushidocodes** [comment]
@albero94 - This one is complete, right? I believe I tested this, but we just are missing migration for when nodes leave.

**Comment by albero94** [comment]
Yes it's done, I probably craeted a duplicate.
