### ISSUE TITLE
Create Data API

### ISSUE THREAD

**Issue by albero94** [bushidocodes/chord-grpc#9]
We need an API with the ability to add, edit, remove, and look up data.

**Comment by heidiklum** [comment]
Should we start a "data.js" file with all the data stuff in it?  I don't think we should cram that into node.js.

For now, I put a dummy "await migrate_keys()" call in "join()", where eventually this migrate_keys would be a wrapper function that calls a bunch of stuff from "data.js" - or whatever that package is called.

Regardless, I placed the dummy "async function migrate_keys(){}" right above "main(){}" to at least keep it grouped after all the chord-specific methods and functions.
